spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pictgram2
    username: pictgram2
    password: password 

  h2:
    console:
      enabled: true
debug: true
image:
  local: true
